source/Docker-backend/pawnshop/adicionales/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.adicionales_home_view,name='adicionales-home'),
path('crear/', views.adicionales_create_view,name='adicionales-crear'),
path('buscar/', views.adicionales_search_view,name='adicionales-buscar'),
path('get/ajax/validate/tabla_adicionales', views.tabla_adicionales, name = "tabla_adicionales"),
]

source/Docker-backend/pawnshop/loans/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.loan_home_view,name='loans-home'),
path('crear/', views.loan_create_view,name='loans-crear'),
path('buscar/', views.loan_search_view,name='loans-buscar'),
path('get/ajax/validate/tabla', views.tabla_prestamo, name = "tabla_prestamo"),
path('cobrarhoy/', views.loan_cobrar_hoy,name='loans-cobrar_hoy'),
path('vencidos/', views.loan_vencidos,name='loans-vencidos'),
path('get/ajax/validate/tabla_cobrar_hoy', views.tabla_cobrar_hoy, name = "tabla_cobrar_hoy"),
]

source/Docker-backend/pawnshop/pawnshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('loans/', include('loans.urls')),
    path('clients/', include('clients.urls')),
    path('abonos/', include('abonos.urls')),
    path('adicionales/', include('adicionales.urls')),
]

source/Docker-backend/pawnshop/adicionales/models.py
from django.db import models

# from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator,MaxValueValidator

from loans.models import Loan



class Adicional(models.Model):
    prestamo        = models.ForeignKey(Loan, on_delete=models.CASCADE)
    adicional       = models.PositiveIntegerField()
    date_created    = models.DateField()          
    
    def __str__(self):
        return f"{self.pk} {self.prestamo}: {self.adicional} - {self.date_created}"
    
    class Meta:
        ordering = ('date_created',)

source/Docker-backend/pawnshop/loans/models.py
import this
from django.db import models
import datetime
from datetime import timedelta
# from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator,MaxValueValidator
from clients.models import Client
from django.conf import settings

User = settings.AUTH_USER_MODEL

def get_deadline(date_created:int,num_meses:int):
    return timedelta(date_created) + timedelta(30*int(num_meses))

# Create your models here.
class TipoPago(models.Model):
    tipo = models.CharField(max_length=200)

    def __str__(self):
        return self.tipo

class Loan(models.Model):
    cliente         = models.ForeignKey(Client, on_delete=models.CASCADE)
    monto_prestado  =  models.PositiveIntegerField(validators=[MaxValueValidator(1000000000)],default=0)
    interes         = models.FloatField(
                        validators=[MinValueValidator(0.0), MaxValueValidator(10.0)],default=0
                    )
    num_meses       = models.PositiveIntegerField(validators=[MaxValueValidator(12)],default=1)
    tipo_pago       = models.ForeignKey(TipoPago, on_delete=models.CASCADE)

    date_created    = models.DateField()      

    num_cuotas      = models.PositiveIntegerField(validators=[MaxValueValidator(1000)],default=1)

    deadline = models.DateField()
    status = models.BooleanField(default=1) #NOTE: Estado del Prestamo 1 = activo, 2 = Inactivo
    last_modification = models.DateField(default=datetime.date.today)
    creador = models.ForeignKey(User,
                        null = True, 
                        on_delete = models.SET_NULL
                        )
    monto_adeudado   = models.PositiveIntegerField(default=0)
    #TODO: Si se paso de la fecha de pago y el prestamo sigue activo se debe cobrar la cuota mensual en la fecha
    #que corresponda a la decorte. Debo pensar como actualizo la tabla.
    
    #se debe agregar una cuota mas a la lista de fechas si el prestamo aún no s ha cancelado. Cambie de opinion.
    
    #Preguntar a alejandro, si el cliente no paga solo se le capitaliza el interes?
    
    # al seleccionar que x cliente no va a pagar la cuota, se actuliza la fecha de pago a la cuota inmediatamente siguiente
    # a la ultima correspondiente al prestamo y se reaiza un adicional, este adicional puede ser opcional.

    
        
    def __str__(self):
        return f"{self.cliente}: {self.monto_prestado} - {self.date_created}"
    
    class Meta:
        ordering = ('pk',)

class EstadoPago(models.Model):
    '''
    Este modelo es para especificar el estado del pago, de estaforma saber si el pago esta:
    - Pago
    - No pago
    - Incompleto
    '''
    tipo = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.pk}: {self.tipo}"
        

class LoanDate(models.Model):
    '''
    Este modelo es para tener el record de los pagos de los clientes y saber las fechas en al que los mismos deben pagar 
    '''
    loan         = models.ForeignKey(Loan, on_delete=models.CASCADE)
    cliente         = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_para_pago    = models.DateField()
    cuota_mensual  =  models.PositiveIntegerField(validators=[MaxValueValidator(1000000000)],default=0)
    status = models.ForeignKey(EstadoPago, on_delete=models.CASCADE)
    
    date_de_pago = models.DateField() #Fecha en que realizaría el pago, que es la misma a la fecha date_para_pago
    retrasado = models.BooleanField(default=0) #NOTE: Sí el pago está retrasado. 1 = verdadero, 2 = falso.

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return f"{self.pk}: {self.loan} {self.cliente} {self.date_para_pago}"

source/Docker-backend/pawnshop/adicionales/views.py
from django.shortcuts import render
from .form import AdicionalForm
from loans.models import Loan
from clients.models import Client
from .models import Adicional
from django.shortcuts import render, redirect
from django.http import JsonResponse

# Create your views here.
def adicionales_home_view(request):
    return render(request, 'adicionales/adicionales_home.html', {})

def adicionales_create_view(request):
    form = AdicionalForm()

    if request.method == 'POST':
        # print(request.POST)
        allpost = request.POST
        form = AdicionalForm(request.POST)
        if form.is_valid():
            # print('Is valid')
            
            #----------
            id_prestamo = allpost.get("prestamo", None)
            print(f"El id del prestamo: {id_prestamo}")
            adicional = allpost.get("adicional", None)
            print(f"El adicional es: {adicional}")
            
            adeudado = list(Loan.objects.filter(pk=id_prestamo).values())[0]["monto_adeudado"]
            print(f"Valor de deuda: {adeudado}")
            # print(f"tipo de dato: {type(adeudado)}")
            new_adeudado = int(adeudado) + int(adicional)
            Loan.objects.filter(pk=id_prestamo).update(monto_adeudado=new_adeudado)
            _adeudado = list(Loan.objects.filter(pk=id_prestamo).values())[0]["monto_adeudado"]
            print(f"Valor del deuda a actualizar: {_adeudado}")

            #----------
            form.save()
            return redirect('/adicionales/')  # 4
        else:  # 5
            # Create an empty form instance
            form = AdicionalForm()

    loans = Loan.objects.all().order_by('cliente')
    clientes = Client.objects.all().order_by('nombre')

    context = {
        'form': form,
        'loans': loans,
        'clientes':clientes,
        }
    return render(request, 'adicionales/adicionales_crear.html', context)

def adicionales_search_view(request):
    return render(request, 'adicionales/adicionales_buscar.html', {})

def tabla_adicionales(request):
    if request.is_ajax and request.method == "GET":
        tables = []
        adicional_table = Adicional.objects.values()
        for adicional in adicional_table:
            cliente_id = list(Loan.objects.filter(pk=adicional["prestamo_id"]).values())[0]["cliente_id"]
            monto_adeudado = list(Loan.objects.filter(pk=adicional["prestamo_id"]).values())[0]["monto_adeudado"]
            cliente_nombre = list(Client.objects.filter(pk=cliente_id).values())[0]["nombre"]
            cliente_apellido = list(Client.objects.filter(pk=cliente_id).values())[0]["apellido"]
            tables.append(
                f'<tr><th scope="row">{cliente_id}</th><td>{cliente_nombre} {cliente_apellido}</td><td>{adicional["id"]}</td><td>{monto_adeudado}</td><td>{adicional["date_created"]}</td><td>{adicional["adicional"]}</td></tr>'
            )
        
        return JsonResponse({"_adicionales_informacion":tables}, status = 200)

        
    return JsonResponse({}, status = 400)

source/Docker-backend/pawnshop/templates/adicionales/adicionales_buscar.html
{% extends '_base.html' %} 
{% load static %}

{% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %}

{% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/base.css' %}"
/>

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/forms.css' %}"
/>

<meta
  name="viewport"
  content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"
/>

<meta name="robots" content="NONE,NOARCHIVE" />

{% endblock css %} 

{% block javascript %}
{% endblock javascript %}



{% block content %} 
<h1>Este es la busqueda de Abonos</h1>
{% endblock content %}

source/Docker-backend/pawnshop/templates/adicionales/adicionales_crear.html
{% extends '_base.html' %} 
{% load static %}

{% block title %}
<title>Abonos | Crear Abonos</title>

<link
  href="{% static 'css/autocomplete/jquery-ui.css' %}"
  rel="stylesheet"
  type="text/css"
/>
{% endblock title %}
   
{% block css %} 
<link href="{% static 'css/client/validation.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

{% block content %} 
  <!-- Content -->

  <div id="content-main">
    <form 
    method="post" 
    id="abono_form" 
    class="border border-secondary"
    action=""
    novalidate
    >
      {% csrf_token %}
      <div>
        <fieldset class="module aligned">
          <legend>
            <strong> Crear nuevo abono</strong>
          </legend>
          <div class="row ml-4 mt-4 mb-4 ID-Cliente">
            <div class="col-1">
              <label class="required" for="id_pk">
                <strong> <h5>ID:</h5> </strong>
              </label>
            </div>
            <div class="col-2">
              <input type="text" id="client-id" name="cliente" required=""/>
              <script>
                $(function () {
                  var availableTags = [
                    {% for cliente in clientes %}
                    {
                      nombre: "{{cliente.nombre}}",
                      label: "{{cliente.pk}}",
                      last_name: "{{cliente.apellido}}",
                    },
                    {% endfor %}
                    // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                    // "{{cliente.nombre}}",
                  ];
                  $("#client-id")
                    .autocomplete({
                      minLength: 0,
                      source: availableTags,
                      focus: function (event, ui) {
                        $("#cliente-name").val(ui.item.nombre + " " + ui.item.last_name);
                        $("#client-id").val(ui.item.label);
                        return false;
                      },
                      select: function (event, ui) {
                        $("#cliente-name").val(ui.item.nombre + " " + ui.item.last_name);
                        $("#client-id").val(ui.item.label);
                        return false;
                      },
                    })
                    .autocomplete("instance")._renderItem = function (ul, item) {
                    return $("<li>")
                      .append(
                        "<div>" +
                          item.label +
                          " " +
                          item.nombre +
                          " " +
                          item.last_name +
                          "</div>"
                      )
                      .appendTo(ul);
                  };
                });
              </script>
            </div>
            <div class="col-1">
              <label class="required" for="id_cliente">
                <strong> <h5>Cliente:</h5> </strong>
              </label>
            </div>
            <div class="col-1">
              <input type="text" id="cliente-name" required=""/>
              <!-- <input type="hidden" id="client-id" name="cliente"> -->
              <script>
                $( function() {
                      var availableTags = [
                      {% for cliente in clientes %}
                      {
                        value: "{{cliente.pk}}",
                        label: "{{cliente.nombre}}",
                        last_name: "{{cliente.apellido}}",
                      },
                      {% endfor %}
                      // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                      // "{{cliente.nombre}}",
                      ];
                      $( "#cliente-name" ).autocomplete({
                                                      minLength: 1,
                                                      source: availableTags,
                                                      focus: function( event, ui ) {
                                                        $( "#cliente-name" ).val( ui.item.value + ' ' + ui.item.label + ' ' + ui.item.last_name );
                                                        return false;
                                                      },
                                                      select: function( event, ui ) {
                                                                                      $( "#cliente-name" ).val( ui.item.label + ' ' + ui.item.last_name );
                                                                                      $( "#client-id" ).val( ui.item.value ).trigger("change");
                                                                                      return false;
                                                                                    }
                                                    })
                      .autocomplete( "instance" )._renderItem = function( ul, item ) {
                      return $( "<li>" )
                        .append( "<div>" + item.value + " " + item.label + " " + item.last_name + "</div>" )
                        .appendTo( ul );
                        };
                  } );
              </script>
            </div>
          </div>
          <div class="row ml-4 mt-4 mb-4 Prestamo-Fecha">
            <div class="col-1">
              <label class="required" for="id_prestamo">
                <strong> <h5>Codigo Prestamo:</h5> </strong>
              </label>
            </div>
            <div class="col-1">
              <select
                type="number"
                name="prestamo"
                required
                id="id_codigo_prestamo"
              />
                <option value="" selected="">---------</option>
              </select>
            </div>
            <div class="col-d-xl-flex">
              <label class="required" for="id_fecha_prestamo">
                <strong> <h5>Fecha de prestamo:</h5> </strong>
              </label>
            </div>
            <div class="col-2">
              <input
                type="date"
                name="date_created_prestamo"
                value="0"
                min="0"
                id="id_date_created_prestamo"
                readonly
              />
            </div>
            <div class="col-d-xl-flex">
              <label class="required" for="id_deadline">
                <strong> <h5>Deadline:</h5> </strong>
              </label>
            </div>
            <div class="col-1">
              <input
                type="date"
                name="deadline"
                size="10"
                id="id_deadline"
                spellcheck="false"
                data-ms-editor="true"
                readonly
              />
            </div>
          </div>
          <div class="row ml-4 mt-4 mb-4 MontoEInteres">
            <div class="col-1">
              <label class="required" for="id_monto_prestado">
                <strong> <h5>Monto prestado:</h5> </strong>
              </label>
            </div>
            <div class="col-auto">
              <input
                type="number"
                name="monto_adeudado"
                value="0"
                min="0"
                id="id_monto_adeudado"
                readonly
              />
            </div>
            <div class="col-auto">
              <label class="required" for="id_interes">
                <strong> <h5>Interes:</h5> </strong>
              </label>
            </div>
            <div class="col-auto">
              <input
                type="number"
                name="interes"
                value="0"
                step="any"
                id="id_interes"
                readonly
              />
            </div>
            <div class="col-1">
              <label class="required" for="id_num_cuotas">
                <strong> <h5>Num cuotas:</h5> </strong>
              </label>
            </div>
            <div class="col-1">
              <input
                type="number"
                name="num_cuotas"
                value="1"
                min="0"
                required=""
                id="id_num_cuotas"
                readonly
              />
            </div>
          </div>
          <div class="row ml-4 mt-4 mb-4 NumMeses-TipoDePago-">
            <div class="col-1">
              <label class="required" for="id_num_meses">
                <strong> <h5>Num meses:</h5> </strong>
              </label>
            </div>
            <div class="col-2">
              <input
                type="number"
                name="num_meses"
                value="1"
                class="vIntegerField"
                min="0"
                id="id_num_meses"
                readonly
              />
            </div>
            <div class="col-1">
              <label class="required" for="id_tipo_pago">
                <strong> <h5>Tipo pago:</h5> </strong>
              </label>
            </div>
            <div class="col-1">
              <input
                type="text"
                name="tipo_pago"
                value=""
                class="vIntegerField"
                min="0"
                id="id_tipo_pago"
                readonly
              />
            </div>
          </div>
          <div class="row ml-4 mt-4 mb-4 FechaUltimoAbono">
            <div class="col-1">
              <label class="required" for="id_Abono_a_pagar">
                <strong> <h5>Último Abono:</h5> </strong>
              </label>
            </div>
            <div class="col-2">
              <input
                type="number"
                name="ultimo_abono"
                value="0"
                min="0"
                required=""
                id="id_ultimo_abono"
                readonly
              />
            </div>
            <div class="col-1">
              <label class="required" for="id_monto_a_pagar">
                <strong> <h5>Fecha Último Abono:</h5> </strong>
              </label>
            </div>
            <div class="col-2">
              <input
                type="date"
                name="fecha_ultimo_abono"
                value="0"
                min="0"
                required=""
                id="id_fecha_ultimo_abono"
                readonly
              />
            </div>
          </div>
          <div class="row ml-4 mt-4 mb-4 AbonoAPagar">
            <div class="col-1">
              <label class="required" for="id_Abono_a_pagar">
                <strong> <h5>Adicional:</h5> </strong>
              </label>
            </div>
            <div class="col-2">
              <input
                type="number"
                name="adicional"
                value="0"
                min="0"
                required=""
                id="id_adicional"
              />
            </div>
            <div class="col-1">
              <label class="required" for="id_fechaAbono">
                <strong> <h5>Fechca de abono:</h5> </strong>
              </label>
            </div>
            <div class="col-1">
              <input
                type="date"
                name="date_created"
                size="10"
                required=""
                id="id_fechaAbono"
                spellcheck="false"
                data-ms-editor="true"
              />
            </div>
          </div>
          
        </fieldset>

        <div class="row float-left mt-3 ml-3">
          <button type="submit" class="btn btn-light ml-3 mr-3 text-dark" name="save">
            <a><strong><h4>Guardar</h4></strong></a>
          </button>
          <button class="btn btn-light ml-3 mr-3">
            <strong><h4><a href="{% url 'adicionales-home' %}" class="text-dark">Cancel</a></h4></strong>
          </button>
        </div>

        </div>
      </div>
    </form>
    <script src="{% static 'js/abonos/IDs_prestamos.js' %}"></script>
    <script src="{% static 'js/abonos/informacion_prestamo.js' %}"></script>
     
  </div>

  <!-- END Content -->
{% endblock content %}

{% block footer %} 
<div id="footer"></div>
{% endblock footer %}

source/Docker-backend/pawnshop/templates/adicionales/adicionales_detalle.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
<title>Detalle Prestamos | Zulumar</title>

<link
  href="{% static 'css/autocomplete/jquery-ui.css' %}"
  rel="stylesheet"
  type="text/css"
/>
{% endblock title %}
   
{% block css %} 
<link href="{% static 'css/client/validation.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

{% block javascript %}
<script src="{% static 'js/abonos/detalle_prestamo_y_cliente.js' %}"></script>
{% endblock javascript %} 



{% block content %}
{% comment %} <h1>Detalles de prestamo {{object.pk}}</h1> {% endcomment %}

<div>
  <fieldset class="module aligned">
    <legend>
      <strong> Detalle de Préstamo</strong>
    </legend>
    <div class="row ml-4 mt-4 mb-4 ID-Cliente">
      <div class="col-auto">
        <label class="required" for="id_pk">
          <h5><strong>ID Cliente:</strong></h5>
        </label>
      </div>
      <div class="col-auto pl-0 pr-5">
        <h5 id="id_client_id" name="cliente_id"> </h5>
      </div>
      <div class="col-auto">
        <label class="required" for="id_cliente">
          <h5> <strong> Nombre Completo:</strong></h5> 
        </label>
      </div>
      <div class="col-auto pr-5 pl-0">
        <h5 id="id_nombre_client" name="nombre_client"> </h5>
      </div>

      <div class="col-auto">
        <label class="required" for="id_prestamo">
          <h5><strong>Codigo Prestamo:</strong></h5>
        </label>
      </div>
      <div class="col-auto pr-5 pl-0">
        <h5 id="id_codigo_prestamo" name="codigo_prestamo">{{object.pk}}</h5>
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 Prestamo-Fecha">
      <div class="col-auto">
        <label class="required" for="id_fecha_prestamo">
          <h5><strong>Fecha de prestamo:</strong></h5>
        </label>
      </div>
      <div class="col-auto pr-5 pl-0">
        <h5 id="id_fecha_prestamo" name="fecha_prestamo"> </h5>
      </div>
      <div class="col-auto">
        <label class="required" for="id_deadline">
          <h5><strong>Fecha Límite:</strong></h5>
        </label>
      </div>
      <div class="col-auto pr-5 pl-0">
        <h5 id="id_deadline" name="deadline"> </h5>
      </div>
      <div class="col-auto">
        <label class="required" for="id_num_meses">
          <h5><strong>Num meses:</strong></h5>
        </label>
      </div>
      <div class="col-auto pr-5 pl-0">
        <h5 id="id_num_meses" name="deadline"> </h5>
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 MontoEInteres">
      <div class="col-1">
        <label class="required" for="id_monto_prestado">
          <h5><strong>Monto prestado:</strong></h5>
        </label>
      </div>
      <div class="col-auto">
        <input
          type="number"
          name="monto_prestado"
          value="0"
          min="0"
          id="id_monto_prestado"
          readonly
        />
      </div>
      <div class="col-1">
        <label class="required" for="id_interes">
          <h5><strong>Interes:</strong></h5>
        </label>
      </div>
      <div class="col-1">
        <input
          type="number"
          name="interes"
          value="0"
          step="any"
          id="id_interes"
          readonly
        />
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 NumMeses-TipoDePago-">
      <div class="col-1">
        <label class="required" for="id_tipo_pago">
          <h5><strong>Tipo pago:</strong></h5> 
        </label>
      </div>
      <div class="col-1">
        <input
          type="text"
          name="tipo_pago"
          value=""
          class="vIntegerField"
          min="0"
          id="id_tipo_pago"
          readonly
        />
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 TotalPagar-NumCuotas">
      <div class="col-1">
        <label class="required" for="id_monto_a_pagar">
          <h5><strong>Monto a pagar:</strong></h5>
        </label>
      </div>
      <div class="col-2">
        <input
          type="number"
          name="monto_a_pagar"
          value="0"
          min="0"
          id="id_monto_a_pagar"
          readonly
        />
      </div>
      <div class="col-1">
        <label class="required" for="id_num_cuotas">
          <h5><strong>Num cuotas:</strong></h5>
        </label>
      </div>
      <div class="col-1">
        <input
          type="number"
          name="num_cuotas"
          value="1"
          min="0"
          required=""
          id="id_num_cuotas"
          readonly
        />
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 FechaUltimoAbono">
      <div class="col-1">
        <label class="required" for="id_monto_a_pagar">
          <h5><strong>Fecha Ultimo Abono:</strong></h5> 
        </label>
      </div>
      <div class="col-2">
        <input
          type="number"
          name="ultimo_abono"
          value="0"
          min="0"
          required=""
          id="id_ultimo_abono"
          readonly
        />
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 AbonoAPagar">
      <div class="col-1">
        <label class="required" for="id_Abono_a_pagar">
          <h5><strong>Abono:</strong></h5>
        </label>
      </div>
      <div class="col-1">
        <input
          type="number"
          name="abono"
          value="0"
          min="0"
          required=""
          id="id_abono_a_pagar"
          readonly
        />
      </div>
    </div>
    <div class="row ml-4 mt-4 mb-4 FechaAbono">
      <div class="col-auto">
        <label class="required" for="id_fechaAbono">
          <h5><strong>Fechca de abono:</strong></h5>
        </label>
      </div>
      <div class="col-1">
        <input
          type="date"
          name="date_created"
          size="10"
          required=""
          id="id_fechaAbono"
          spellcheck="false"
          data-ms-editor="true"
          readonly
        />
      </div>
    </div>
  </fieldset>
</div>

{% endblock content %}

source/Docker-backend/pawnshop/templates/adicionales/adicionales_home.html
{% extends '_base.html' %} {% load static %} {% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %} {% block css %} {% endblock css %} {% block javascript %}
<script src="{% static 'js/adicionales/tablas_adicionales.js' %}"></script>

<script src="{% static 'js/client/clients-pie-charts.js' %}"></script>
{% comment %}
<script src="{% static 'js/client/clients-bar-charts.js' %}"></script>
{% endcomment %} {% endblock javascript %} {% block content %}

<div class="Superior">
  <div class="row float-left mt-1 ml-3 mb-1 mr-1">
    <h2 style=""><strong>Resumen de Clientes</strong></h2>
  </div>
  <div class="row float-right mt-1 ml-3 mb-1 mr-1">
    <a class="p-2 text-dark" href="{% url 'adicionales-crear' %}">
      <img src="{% static 'images/base/add.png' %}" alt="" height="25" />
    </a>
    <a class="p-2 text-dark" href="{% url 'clients-buscar' %}">
      <img src="{% static 'images/base/search3.png' %}" alt="" height="25" />
    </a>
  </div>
</div>

<div class=" " style="display: flex; margin-left: 50px">
  <div class="col-7 card ml-2 mr-2">
    <div class="card-body">
      <h4 class="card-title" style="margin-left: 250px">Adicionales Regitrados</h4>
      <p class="card-description" style="margin-left: 250px">
        Información básica de Adicionales
      </p>

      <div
        class="tablewrapper"
        style="width: 800px; margin-left: 10px; max-height: 400px"
      >
        <table class="table">
          <thead>
            <tr class="h4 text-center">
              <th scope="col">ID Cliente</th>
              <th scope="col">Nombre cliente</th>
              <th scope="col">Codigo de Adicional</th>
              <th scope="col">Monto Adeudado</th>
              <th scope="col">Fecha de Adicional</th>
              <th scope="col">Monto Adicionado</th>
            </tr>
          </thead>
          <tbody id="id_tabla_prestamo" class="h4 text-center">
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-4.7 flex-box" >
    
    <div class="card " style="margin-right:20px">
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de clientes creados</h4>
        <p class="card-description text-center"> Entre Enero y mayo de 2022</p>
        <div class="chart-container" style=" margin: 50px; ">
          <canvas id="bar-chart" ></canvas>
        </div>
      </div>
    </div>
        <div class="card" style="margin-right:20px" >
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de clientes creados</h4>
        <div class="chart-container" style="width: 30%; margin-left: 160px">
          <canvas height="60px" id="pie-chart"></canvas>
        </div>
      </div>
  </div> 

</div>

{% endblock content %}