source/Docker-backend/pawnshop/loans/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.loan_home_view,name='loans-home'),
path('crear/', views.loan_create_view,name='loans-crear'),
path('buscar/', views.loan_search_view,name='loans-buscar'),
path('get/ajax/validate/tabla', views.tabla_prestamo, name = "tabla_prestamo"),
path('cobrarhoy/', views.loan_cobrar_hoy,name='loans-cobrar_hoy'),
path('vencidos/', views.loan_vencidos,name='loans-vencidos'),
path('get/ajax/validate/tabla_cobrar_hoy', views.tabla_cobrar_hoy, name = "tabla_cobrar_hoy"),
]

source/Docker-backend/pawnshop/pawnshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('loans/', include('loans.urls')),
    path('clients/', include('clients.urls')),
    path('abonos/', include('abonos.urls')),
    path('adicionales/', include('adicionales.urls')),
]

source/Docker-backend/pawnshop/loans/models.py
import this
from django.db import models
import datetime
from datetime import timedelta
# from django.core.validators import RegexValidator
from django.core.validators import MinValueValidator,MaxValueValidator
from clients.models import Client
from django.conf import settings

User = settings.AUTH_USER_MODEL

def get_deadline(date_created:int,num_meses:int):
    return timedelta(date_created) + timedelta(30*int(num_meses))

# Create your models here.
class TipoPago(models.Model):
    tipo = models.CharField(max_length=200)

    def __str__(self):
        return self.tipo

class Loan(models.Model):
    cliente         = models.ForeignKey(Client, on_delete=models.CASCADE)
    monto_prestado  =  models.PositiveIntegerField(validators=[MaxValueValidator(1000000000)],default=0)
    interes         = models.FloatField(
                        validators=[MinValueValidator(0.0), MaxValueValidator(10.0)],default=0
                    )
    num_meses       = models.PositiveIntegerField(validators=[MaxValueValidator(12)],default=1)
    tipo_pago       = models.ForeignKey(TipoPago, on_delete=models.CASCADE)

    date_created    = models.DateField()      

    num_cuotas      = models.PositiveIntegerField(validators=[MaxValueValidator(1000)],default=1)

    deadline = models.DateField()
    status = models.BooleanField(default=1) #NOTE: Estado del Prestamo 1 = activo, 2 = Inactivo
    last_modification = models.DateField(default=datetime.date.today)
    creador = models.ForeignKey(User,
                        null = True, 
                        on_delete = models.SET_NULL
                        )
    monto_adeudado   = models.PositiveIntegerField(default=0)
    #TODO: Si se paso de la fecha de pago y el prestamo sigue activo se debe cobrar la cuota mensual en la fecha
    #que corresponda a la decorte. Debo pensar como actualizo la tabla.
    
    #se debe agregar una cuota mas a la lista de fechas si el prestamo aún no s ha cancelado. Cambie de opinion.
    
    #Preguntar a alejandro, si el cliente no paga solo se le capitaliza el interes?
    
    # al seleccionar que x cliente no va a pagar la cuota, se actuliza la fecha de pago a la cuota inmediatamente siguiente
    # a la ultima correspondiente al prestamo y se reaiza un adicional, este adicional puede ser opcional.

    
        
    def __str__(self):
        return f"{self.cliente}: {self.monto_prestado} - {self.date_created}"
    
    class Meta:
        ordering = ('pk',)

class EstadoPago(models.Model):
    '''
    Este modelo es para especificar el estado del pago, de estaforma saber si el pago esta:
    - Pago
    - No pago
    - Incompleto
    '''
    tipo = models.CharField(max_length=200)

    def __str__(self):
        return f"{self.pk}: {self.tipo}"
        

class LoanDate(models.Model):
    '''
    Este modelo es para tener el record de los pagos de los clientes y saber las fechas en al que los mismos deben pagar 
    '''
    loan         = models.ForeignKey(Loan, on_delete=models.CASCADE)
    cliente         = models.ForeignKey(Client, on_delete=models.CASCADE)
    date_para_pago    = models.DateField()
    cuota_mensual  =  models.PositiveIntegerField(validators=[MaxValueValidator(1000000000)],default=0)
    status = models.ForeignKey(EstadoPago, on_delete=models.CASCADE)
    
    date_de_pago = models.DateField() #Fecha en que realizaría el pago, que es la misma a la fecha date_para_pago
    retrasado = models.BooleanField(default=0) #NOTE: Sí el pago está retrasado. 1 = verdadero, 2 = falso.

    class Meta:
        ordering = ('pk',)

    def __str__(self):
        return f"{self.pk}: {self.loan} {self.cliente} {self.date_para_pago}"

source/Docker-backend/pawnshop/loans/views.py
from unicodedata import numeric
from django.shortcuts import render, redirect
from .form import LoanForm
from .models import TipoPago, LoanDate,EstadoPago
from clients.models import Client
from .models import Loan
from django.http import JsonResponse
from dateutil.relativedelta import relativedelta


import datetime


def loan_create_view(request):
    form = LoanForm()


    if request.method == 'POST':
        # print(request.POST)
        form = LoanForm(request.POST)
        # cliente = request.POST['cliente']
        # print(f'El cliente es: {cliente}')
        # print(f'el ultimo pk: {lastest_pk.pk}')
        
        # estado_pago = EstadoPago.objects.all().order_by('pk')
        # print(estado_pago)
        
        if form.is_valid():
            print('Is valid')
            form.save()
            
            _loan = Loan.objects.latest('pk')
            _cliente = Client.objects.get(pk=request.POST['cliente']) 
            _num_cuotas = int(request.POST['num_cuotas'])
            _monto_adeudado = request.POST['monto_adeudado']
            _cuota_mensual = float(int(_monto_adeudado)/int(_num_cuotas))
            tipo_pago = request.POST['tipo_pago']
            # retrasado = request.POST['']
            _status = EstadoPago.objects.get(pk='3') 

            print(f'_loan: {_loan}')
            print(f'cuota de: {_cuota_mensual}')
            print(f'Cliente: {_cliente}')

            #estas fechas se deben calcular con un for, teniendo en cuenta el tipo de pago elegido por el cliente
            _date_created = request.POST['date_created']
            _date = _date_created.replace('-', ' ').split(' ')
            _day_date = int(_date[2])
            _month_date = int(_date[1])
            _year_date = int(_date[0])
            _date_created_ = datetime.date(_year_date, _month_date, _day_date)

            for plazo in range(1,_num_cuotas + 1):
                if tipo_pago == '1':
                    _date_para_pago = _date_created_ + relativedelta(months=plazo)
                    loan_date = LoanDate(loan=_loan,
                                         cliente=_cliente,
                                         date_para_pago=_date_para_pago,
                                         cuota_mensual=_cuota_mensual,
                                         status=_status,
                                         date_de_pago = _date_para_pago)

                    loan_date.save()
                    last_loan_date = LoanDate.objects.latest('pk')
                    print(f'Last loan date: {last_loan_date}')
                
                #Verificar funcionamiento
                elif tipo_pago == '2':
                    _date_para_pago = _date_created_ + relativedelta(days=(plazo*15))
                    loan_date = LoanDate(loan=_loan,
                                         cliente=_cliente,
                                         date_para_pago=_date_para_pago,
                                         cuota_mensual=_cuota_mensual,
                                         status=_status,
                                         date_de_pago = _date_para_pago)

                    loan_date.save()
                    last_loan_date = LoanDate.objects.latest('pk')
                    print(f'Last loan date: {last_loan_date}')
                #Verificar funcionamiento
                elif tipo_pago == '3':
                    _date_para_pago = _date_created_ + relativedelta(weeks=plazo)
                    loan_date = LoanDate(loan=_loan,
                                         cliente=_cliente,
                                         date_para_pago=_date_para_pago,
                                         cuota_mensual=_cuota_mensual,
                                         status=_status,
                                         date_de_pago = _date_para_pago)

                    loan_date.save()
                    last_loan_date = LoanDate.objects.latest('pk')
                    print(f'Last loan date: {last_loan_date}')
                #Verificar funcionamiento
                elif tipo_pago == '4':
                    _date_para_pago = _date_created_ + relativedelta(days=(plazo))
                    loan_date = LoanDate(loan=_loan,
                                         cliente=_cliente,
                                         date_para_pago=_date_para_pago,
                                         cuota_mensual=_cuota_mensual,
                                         status=_status,
                                         date_de_pago = _date_para_pago)

                    loan_date.save()
                    last_loan_date = LoanDate.objects.latest('pk')
                    print(f'Last loan date: {last_loan_date}')

            return redirect('/loans/')  # 4
        else:  # 5
            # Create an empty form instance
            form = LoanForm()
    tipo_pagos = TipoPago.objects.all().order_by('pk')
    clientes = Client.objects.all().order_by('nombre')

    context = {
        'form': form,
        'tipo_pagos': tipo_pagos,
        'clientes': clientes,
        }
    return render(request, 'loans/prestamos_crear.html', context)

def loan_home_view(request):
    clientes = Client.objects.all().order_by('pk')
    prestamos = Loan.objects.all().order_by('pk')

    context = {
        'clientes': clientes,
        'prestamos': prestamos,

         }
    return render(request, 'loans/prestamos_home.html', context)

def loan_search_view(request):
    return render(request, 'loans/prestamos_buscar.html', {})

def tabla_prestamo(request):
    if request.is_ajax and request.method == "GET":
        tables = []
        loans_table = Loan.objects.values()
        for prestamo in loans_table:
            # cliente = list(Client.objects.filter(pk=prestamo.cliente))
            cliente_nombre = list(Client.objects.filter(pk=prestamo["cliente_id"]).values())[0]["nombre"]
            cliente_apellido = list(Client.objects.filter(pk=prestamo["cliente_id"]).values())[0]["apellido"]
            tables.append(
                f'<tr><th scope="row">{prestamo["id"]}</th><td>{prestamo["monto_prestado"]}</td><td>{prestamo["monto_adeudado"]}</td><td>{prestamo["num_meses"]}</td><td>{prestamo["cliente_id"]}</td><td>{cliente_nombre} {cliente_apellido}</td></tr>'
            )
        
        return JsonResponse({"_prestamo_imformacion":tables}, status = 200)

        
    return JsonResponse({}, status = 400)

# Sin finalizar

def loan_cobrar_hoy(request):
    loan_date = LoanDate.objects.all().order_by('pk')
    context = {
    'loan_date': loan_date,
        }
    return render(request, 'loans/prestamos_cobrar_hoy.html',context)

def loan_vencidos(request):
    return render(request, 'loans/prestamos_vencidos.html')

def tabla_cobrar_hoy(request):
    if request.is_ajax and request.method == "GET":
        tables = []
        # fecha_hoy = request.GET.get("fecha_hoy", None)
        #filtra los prestamos que aun estan activos
        _fecha_hoy = request.GET["fecha_hoy"]
        cobrar_hoy_table = LoanDate.objects.filter(date_para_pago=_fecha_hoy,status=EstadoPago.objects.get(pk='3')).values()
        # print(cobrar_hoy_table)
        for cobrar_hoy in cobrar_hoy_table:
            # cliente = list(Client.objects.filter(pk=prestamo.cliente))
            cliente_nombre = list(Client.objects.filter(pk=cobrar_hoy["cliente_id"]).values())[0]["nombre"]
            cliente_apellido = list(Client.objects.filter(pk=cobrar_hoy["cliente_id"]).values())[0]["apellido"]
            # print(cliente_nombre)
            tables.append(
                f'<tr><th scope="row">{cobrar_hoy["id"]}</th><td>{cobrar_hoy["loan_id"]}</td><td>{cobrar_hoy["date_para_pago"]}</td><td>{cobrar_hoy["cuota_mensual"]}</td><td>{cobrar_hoy["cliente_id"]}</td><td>{cliente_nombre} {cliente_apellido}</td></tr>'
            )

        # print(tables)
        
        return JsonResponse({"table_loan_date":tables}, status = 200)

        
    return JsonResponse({}, status = 400)

source/Docker-backend/pawnshop/templates/loans/prestamos_buscar.html
{% extends 'base.html' %} 
{% load static %}

{% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %}

{% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/base.css' %}"
/>

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/forms.css' %}"
/>

<meta
  name="viewport"
  content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"
/>

<meta name="robots" content="NONE,NOARCHIVE" />

{% endblock css %} 

{% block javascript %}
{% endblock javascript %}



{% block content %} 
<h1>Este es la busqueda de prestamos</h1>
{% endblock content %}

source/Docker-backend/pawnshop/templates/loans/prestamos_cobrar_hoy.html
{% extends '_base.html' %} {% load static %} {% block title %}
<title>Préstamos | Home</title>
{% endblock title %} 



{% block content %}



<div class="Superior">
  <div class="row float-left mt-1 ml-3 mb-1 mr-1">
    <h2><strong><a href="{% url 'loans-home' %}" style="color: black;"> Resumen de Prestamos</a></strong></h2>
 
    </div>
    <div class="row float-right mt-1 ml-3 mb-1 mr-1">
      <a class="p-2 text-dark" href="{% url 'loans-crear' %}">
        <img src="{% static 'images/base/add.png' %}" alt="" height="25"/>
      </a>
      
      <a class="p-2 text-dark" href="{% url 'loans-buscar' %}">
        <img src="{% static 'images/base/search3.png' %}" alt="" height="25"/>
      </a>
    </div>
   
  </div>
    

</div>

<div class="">
  <div class="row  ml-3 mt-1 mb-1" style="margin-left:30px">
    <div class=" col-1">
      <label class="required" for="id_monto_prestado">
        <strong> <h5>Fecha de prestamo:</h5> </strong>
      </label>
    </div>
    <div class="col-1">
      <input
        type="date"
        name="fecha_hoy"
        value="0"
        min="0"
        required=""
        id="id_fecha_hoy"
      />
      
    </div>
    
  </div>
  <div>
    <button  type="button" class="btn btn-light ml-3 mr-3" id="id_buscar_fecha" >
      <strong><h4>Buscar</h4></strong>
    </button>
  </div>





</div>



<div class=" " style="display: flex; margin-left: 50px">
  <div class="col-7 card ml-3 mr-3 ">
    <div class="card-body">
      <h4 class="card-title">Cleintes con fecha de pago para Hoy</h4>
      <p class="card-description"> Lista de todos los clientes que aún no han pagado </p>

      <div class="tablewrapper">
        <table class="table">
          <thead>
            <tr class="h4 text-center">
              <th scope="col">Cobrar hoy ID</th>
              <th scope="col">Loan ID</th>
              <th scope="col">Fecha de pago</th>
              <th scope="col">Cuota mensual</th>
              <th scope="col">ID Cliente</th>
              <th scope="col">Nombre cliente</th>
            </tr>
          </thead>
          <tbody id="id_tabla_prestamo" class="h4 text-center">
          </tbody>
        </table>

      </div>
    </div>
  </div>
  <div class="col-4.7 flex-box" >
    
    <div class="card " style="margin-right:20px">
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de clientes creados</h4>
        <p class="card-description text-center"> Entre Enero y mayo de 2022</p>
        <div class="chart-container" style=" margin: 50px; ">
          <canvas id="bar-chart" ></canvas>
        </div>
      </div>
    </div>
        <div class="card" style="margin-right:20px" >
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de clientes creados</h4>
        <div class="chart-container" style="width: 30%; margin-left: 160px">
          <canvas height="60px" id="pie-chart"></canvas>
        </div>
      </div>
  </div> 
 
</div>
<script src="{% static 'js/client/clients-pie-charts.js' %}"></script> 
{% comment %} estoy tomando el ejemplo de clientes, debo hacer uno propio para prestamos {% endcomment %}
<script src="{% static 'js/loan/tabla_cobrar_hoy_loan.js' %}"></script>
{% endblock content %}

source/Docker-backend/pawnshop/templates/loans/prestamos_crear.html
{% extends '_base.html' %} {% load static %} {% block title %}
<title>Add loan</title>

<link
  href="{% static 'css/autocomplete/jquery-ui.css' %}"
  rel="stylesheet"
  type="text/css"
/>
{% endblock title %}  {% block content %}
<!-- Content -->
<div id="content-main">
  <form
    method="post"
    id="loan_form"
    novalidate=""
    class="border border-secondary"
  >
    {% csrf_token %}

    <fieldset class="module aligned">
      <legend class="ml-4">
        <strong> Crear nuevo préstamo</strong>
      </legend>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_pk">
            <strong> <h5>ID:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input type="text" id="client-id" name="cliente" />
          <script>
            $(function () {
              var availableTags = [
                {% for cliente in clientes %}
                {
                  nombre: "{{cliente.nombre}}",
                  label: "{{cliente.pk}}",
                  last_name: "{{cliente.apellido}}",
                },
                {% endfor %}
                // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                // "{{cliente.nombre}}",
              ];
              $("#client-id")
                .autocomplete({
                  minLength: 0,
                  source: availableTags,
                  focus: function (event, ui) {
                    $("#client-id").val(ui.item.label);
                    return false;
                  },
                  select: function (event, ui) {
                    $("#cliente-name").val(ui.item.nombre + " " + ui.item.last_name);
                    $("#client-id").val(ui.item.label);
                    return false;
                  },
                })
                .autocomplete("instance")._renderItem = function (ul, item) {
                return $("<li>")
                  .append(
                    "<div>" +
                      item.label +
                      " " +
                      item.nombre +
                      " " +
                      item.last_name +
                      "</div>"
                  )
                  .appendTo(ul);
              };
            });
          </script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_cliente">
            <strong> <h5>Cliente:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input type="text" id="cliente-name" />
          <!-- <input type="hidden" id="client-id" name="cliente"> -->
          <script>
            $( function() {
                  var availableTags = [
                  {% for cliente in clientes %}
                  {
                    value: "{{cliente.pk}}",
                    label: "{{cliente.nombre}}",
                    last_name: "{{cliente.apellido}}",
                  },
                  {% endfor %}
                  // "{{cliente.pk}} {{cliente.nombre}} {{cliente.apellido}}",
                  // "{{cliente.nombre}}",
                  ];
                  $( "#cliente-name" ).autocomplete({
                                                  minLength: 1,
                                                  source: availableTags,
                                                  focus: function( event, ui ) {
                                                    $( "#cliente-name" ).val( ui.item.value + ' ' + ui.item.label + ' ' + ui.item.last_name );
                                                    return false;
                                                  },
                                                  select: function( event, ui ) {
                                                                                  $( "#cliente-name" ).val( ui.item.label + ' ' + ui.item.last_name );
                                                                                  $( "#client-id" ).val( ui.item.value );
                                                                                  return false;
                                                                                }
                                                })
                  .autocomplete( "instance" )._renderItem = function( ul, item ) {
                  return $( "<li>" )
                    .append( "<div>" + item.value + " " + item.label + " " + item.last_name + "</div>" )
                    .appendTo( ul );
                    };
              } );
          </script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_monto_prestado">
            <strong> <h5>Fecha de prestamo:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="date"
            name="date_created"
            value="0"
            min="0"
            required=""
            id="id_date_created"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_monto_prestado">
            <strong> <h5>Monto prestado:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="monto_prestado"
            value="0"
            min="0"
            required=""
            id="id_monto_prestado"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_interes">
            <strong> <h5>Interes:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="interes"
            value="0"
            step="any"
            required=""
            id="id_interes"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_num_meses">
            <strong> <h5>Num meses:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="num_meses"
            value="1"
            class="vIntegerField"
            min="0"
            required=""
            id="id_num_meses"
          />
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_tipo_pago">
            <strong> <h5>Tipo pago:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <select
            name="tipo_pago"
            required=""
            id="id_tipo_pago"
            onchange="NumCuotas(event)"
          >
            <option value="" selected="">---------</option>
            {% for tipo_pago in tipo_pagos %}
            <option value="{{tipo_pago.pk}}">{{tipo_pago.tipo}}</option>
            {% endfor %}
          </select>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_monto_a_pagar">
            <strong> <h5>Monto a pagar:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="monto_adeudado"
            value="0"
            min="0"
            required=""
            id="id_monto_adeudado"
            readonly
          />
          <script src="{% static 'js/loan/montoapagar.js' %}"></script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_num_cuotas">
            <strong> <h5>Num cuotas:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="number"
            name="num_cuotas"
            value="1"
            min="0"
            required=""
            id="id_num_cuotas"
          />
          <script src="{% static 'js/loan/numeroCuotas.js' %}"></script>
        </div>
      </div>
      <div class="row ml-4 mt-4 mb-4">
        <div class="col-1">
          <label class="required" for="id_deadline">
            <strong> <h5>Deadline:</h5> </strong>
          </label>
        </div>
        <div class="col-1">
          <input
            type="date"
            name="deadline"
            size="10"
            required=""
            id="id_deadline"
            spellcheck="false"
            data-ms-editor="true"
          />
          <script src="{% static 'js/loan/dead_line.js' %}"></script>
        </div>
      </div>
      
      <div>
        <input type="hidden" id="id_creador" name="creador" value ={{ user.pk }}  />
        {% comment %} <input type="number" id="id_monto_adeudado" name="monto_adeudado" value=""  /> {% endcomment %}
      </div>
      
    </fieldset>
    <div class="row float-left mt-3 ml-3">
      <button type="submit" class="btn btn-light ml-3 mr-3" name="save">
        <strong><h4>Guardar</h4></strong>
      </button>
      <button class="btn btn-light ml-3 mr-3">
        <strong><h4><a href="{% url 'loans-home' %}" class="text-dark">Cancel</a></h4></strong>
      </button>
    </div>
  </form>
</div>
<!-- END Content -->
{% endblock content %} {% block footer %}
<div id="footer"></div>
{% endblock footer %}

source/Docker-backend/pawnshop/templates/loans/prestamos_home.html
{% extends '_base.html' %} {% load static %} {% block title %}
<title>Préstamos | Home</title>
{% endblock title %} 



{% block content %}



<div class="Superior">
  <div class="row float-left  ml-3 mb-1 mr-1">
    <h2><strong>Resumen de Prestamos</strong></h2>
    <div class="row" style="margin-left:300px">
      <h3><strong><a href="{% url 'loans-vencidos' %}" style="color: #111;margin-right:20px;font-size:20px" > Vencidos<a/></strong></button></h3>
      <h3><strong><a href="{% url 'loans-cobrar_hoy' %}" style="color: #111; font-size:20px" >Cobrar Hoy</a></strong></h3>

    </div>

  </div>
    


  <div class="float-right  ml-3 mb- mr-1">
    <a class="p-2 text-dark" href="{% url 'loans-crear' %}">
      <img src="{% static 'images/base/add.png' %}" alt="" height="25"/>
    </a>
    
    <a class="p-2 text-dark" href="{% url 'loans-buscar' %}">
      <img src="{% static 'images/base/search3.png' %}" alt="" height="25"/>
    </a>
  </div>
</div>

<div class=" "style="display: flex; margin-left: 50px">
  <div class="col-7 card ml-3 mr-3 ">
    <div class="card-body">
      <h4 class="card-title" style="margin-left: 250px">Prestamos Regitrados</h4>
      <p class="card-description" style="margin-left: 250px"> Información básica de Prestamo </p>

      <div class="tablewrapper" style="width: 800px;  max-height: 400px">
        <table class="table">
          <thead>
            <tr class="h4 text-center">
              <th scope="col">Codigo prestamo</th>
              <th scope="col">Monto prestado</th>
              <th scope="col">Monto adeudado</th>
              <th scope="col">Numero de meses</th>
              <th scope="col">ID Cliente</th>
              <th scope="col">Nombre cliente</th>
            </tr>
          </thead>
          <tbody id="id_tabla_prestamo" class="h4 text-center">
          </tbody>
        </table>

      </div>
    </div>
  </div>
  <div class="col-4.7 flex-box" >
    
    <div class="card " style="margin-right:20px">
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de Prestamos creados</h4>
        <p class="card-description text-center"> Entre Enero y mayo de 2022</p>
        <div class="chart-container" style=" margin: 50px; ">
          <canvas id="bar-chart" ></canvas>
        </div>
      </div>
    </div>
        <div class="card" style="margin-right:20px" >
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de Prestamos creados</h4>
        <div class="chart-container" style="width: 30%; margin-left: 160px">
          <canvas height="60px" id="pie-chart"></canvas>
        </div>
      </div>
  </div> 
</div>
{% comment %} estoy tomando el ejemplo de clientes, debo hacer uno propio para prestamos {% endcomment %}
<script src="{% static 'js/client/clients-pie-charts.js' %}"></script>
<script src="{% static 'js/loan/tabla_loan.js' %}"></script>
{% endblock content %}

source/Docker-backend/pawnshop/templates/loans/tipopagos.html
{% extends '_base.html' %}
{%load static%}

{% block css %}
<!-- CSS -->
<link rel="stylesheet" href="{% static 'css/base.css' %}">
{% endblock css %}

{% block title %}
<title>
Home
</title>
{% endblock %} 

{% block header%} 
{% if user.is_authenticated %} 
Hi {{ user.username }}!
<p><a href="{% url 'logout' %}">logout</a></p>
{% else %}
<p>You are not logged in</p>
<a href="{% url 'login' %}">login</a> |<a href="{% url 'signup' %}">signup</a>
{% endif %} {% endblock %}

{% block content %} 
<h3>Tipo pago Form</h3>
<hr />

<form action="" method="POST">
  {% csrf_token %} 

  <div class="form-row field-tipo_pago">
    <div>
      <label class="required" for="id_tipo_de_pago">Tipo de pago:</label>

      <div class="related-widget-wrapper">
        <select name="tipo_de_pago" required="" id="id_tipo_pago">
            <option value="" selected="">---------</option>
            {% for object in objects %}
            <option value="{{object.pk}}">{{object.tipo}}</option>
            {% endfor %}
        </select>
      </div>
    </div>
  </div>

  <input type="submit" />
</form>
{% endblock content %}