source/Docker-backend/pawnshop/clients/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.client_home_view, name="clients-home"),
path('crear/', views.client_create_view, name="clients-crear"),
path('buscar/', views.client_search_view, name="clients-buscar"),
]

source/Docker-backend/pawnshop/loans/urls.py
from django.urls import path
from . import views
urlpatterns = [
path('', views.loan_home_view,name='loans-home'),
path('crear/', views.loan_create_view,name='loans-crear'),
path('buscar/', views.loan_search_view,name='loans-buscar'),
path('get/ajax/validate/tabla', views.tabla_prestamo, name = "tabla_prestamo"),
path('cobrarhoy/', views.loan_cobrar_hoy,name='loans-cobrar_hoy'),
path('vencidos/', views.loan_vencidos,name='loans-vencidos'),
path('get/ajax/validate/tabla_cobrar_hoy', views.tabla_cobrar_hoy, name = "tabla_cobrar_hoy"),
]

source/Docker-backend/pawnshop/pawnshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.views.generic.base import TemplateView

urlpatterns = [
    path('', TemplateView.as_view(template_name='home.html'), name='home'),
    path('admin/', admin.site.urls),
    path('users/', include('users.urls')),
    path('users/', include('django.contrib.auth.urls')),
    path('loans/', include('loans.urls')),
    path('clients/', include('clients.urls')),
    path('abonos/', include('abonos.urls')),
    path('adicionales/', include('adicionales.urls')),
]

source/Docker-backend/pawnshop/clients/models.py
from django.db import models
from django.core.validators import RegexValidator
import datetime
from django.conf import settings

User = settings.AUTH_USER_MODEL

# Create your models here.
class Client(models.Model):
    nombre = models.CharField(max_length=200,null=False)
    apellido = models.CharField(max_length=200,null=False)
    cedula = models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')],null=False)
    telefono = models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')],null=False)
    direccion = models.CharField(max_length=200,null=False)
    direccion2 = models.CharField(max_length=200,blank=True)

    ref1 = models.CharField(max_length=200,blank=True)
    telefono_ref1 = models.CharField(max_length=10, validators=[RegexValidator(r'^\d{1,10}$')], blank=True)
    
    status = models.BooleanField(default=1) #NOTE: Cliente con prestamo activo. 1 = activo, 2 = Inactivo
    fecha_creacion = models.DateField(default=datetime.date.today)
    creador = models.ForeignKey(User,
                        null = True, 
                        on_delete = models.SET_NULL
                        )
    def __str__(self):
        return f"{self.nombre} {self.apellido}"
    
    class Meta:
        ordering = ('pk',)

source/Docker-backend/pawnshop/clients/views.py
from django.shortcuts import render, redirect
from .form import ClientForm
from .models import Client


def client_create_view(request):
    form = ClientForm()

    if request.method == 'POST':
        print(request.POST)
        form = ClientForm(request.POST)
        if form.is_valid():
            print('Is valid')
            form.save()
            return redirect('/clients/')  # 4
        else:  # 5
            # Create an empty form instance
            print('Is not valid')
            form = ClientForm()

    context = {
        'form': form,
         }
    return render(request, 'clients/clientes_crear.html', context)


def client_home_view(request):
    clientes = Client.objects.all().order_by('pk')
    context = {
        'clientes': clientes,
         }
    return render(request, 'clients/clientes_home.html', context)

def client_search_view(request):
    return render(request, 'clients/clientes_buscar.html', {})

source/Docker-backend/pawnshop/templates/clients/clientes_buscar.html
{% extends '_base.html' %} 
{% load static %}

{% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %}

{% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/base.css' %}"
/>

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/forms.css' %}"
/>

<meta
  name="viewport"
  content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"
/>

<meta name="robots" content="NONE,NOARCHIVE" />

{% endblock css %} 

{% block javascript %}
{% endblock javascript %}



{% block content %} 
<h1>Este es la busqueda de Clientes</h1>
{% endblock content %}

source/Docker-backend/pawnshop/templates/clients/clientes_crear backup.html
{% extends '_base.html' %} 
{% load static %}

{% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %}

{% block css %}
<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/base.css' %}"
/>

<link
  rel="stylesheet"
  type="text/css"
  href="{% static 'css/loan/forms.css' %}"
/>

<meta
  name="viewport"
  content="user-scalable=no, width=device-width, initial-scale=1.0, maximum-scale=1.0"
/>

<meta name="robots" content="NONE,NOARCHIVE" />

{% endblock css %} 

{% block javascript %}
{% endblock javascript %}
  


{% block content %} 
  <!-- Content -->
  <div id="content" class="colM">
    <h1>Add client</h1>

    <div id="content-main">
      <form method="post" id="client_form" novalidate="">
        {% csrf_token %}
        <div>
          <fieldset class="module aligned">
            <div class="form-row field-nombre">
              <div>
                <label class="required" for="id_nombre">Nombre:</label>

                <input
                  type="text"
                  name="nombre"
                  class="vTextField"
                  maxlength="200"
                  required=""
                  id="id_nombre"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-apellido">
              <div>
                <label class="required" for="id_apellido"
                  >Apellido:</label
                >

                <input
                  type="text"
                  name="apellido"
                  class="vTextField"
                  maxlength="200"
                  required=""
                  id="id_apellido"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-cedula">
              <div>
                <label class="required" for="id_cedula">Cedula:</label>

                <input
                  type="text"
                  name="cedula"
                  class="vTextField"
                  maxlength="10"
                  required=""
                  id="id_cedula"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-telefono">
              <div>
                <label class="required" for="id_telefono"
                  >Telefono:</label
                >

                <input
                  type="text"
                  name="telefono"
                  class="vTextField"
                  maxlength="10"
                  required=""
                  id="id_telefono"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-direccion">
              <div>
                <label class="required" for="id_direccion"
                  >Direccion:</label
                >

                <input
                  type="text"
                  name="direccion"
                  class="vTextField"
                  maxlength="200"
                  required=""
                  id="id_direccion"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-direccion2">
              <div>
                <label class="required" for="id_direccion2"
                  >Direccion2:</label
                >

                <input
                  type="text"
                  name="direccion2"
                  class="vTextField"
                  maxlength="200"
                  required=""
                  id="id_direccion2"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-ref1">
              <div>
                <label class="required" for="id_ref1">Ref1:</label>

                <input
                  type="text"
                  name="ref1"
                  class="vTextField"
                  maxlength="200"
                  required=""
                  id="id_ref1"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>

            <div class="form-row field-telefono_ref1">
              <div>
                <label class="required" for="id_telefono_ref1"
                  >Telefono ref1:</label
                >

                <input
                  type="text"
                  name="telefono_ref1"
                  class="vTextField"
                  maxlength="10"
                  required=""
                  id="id_telefono_ref1"
                  spellcheck="false"
                  data-ms-editor="true"
                />
              </div>
            </div>
          </fieldset>

          <div class="submit-row">
            <input
              type="submit"
              value="Save"
              class="default"
              name="_save"
            />

            <input
              type="submit"
              value="Save and add another"
              name="_addanother"
            />

          </div>
        </div>
      </form>
    </div>

    <br class="clear" />
  </div>
  <!-- END Content -->
{% endblock content %}

{% block footer %} 
<div id="footer"></div>
{% endblock footer %}

source/Docker-backend/pawnshop/templates/clients/clientes_crear.html
{% extends '_base.html' %} 
{% load static %}

{% block title %}
<title>Clientes | Crear Clientes</title>
{% endblock title %}
   
{% block css %} 
<link href="{% static 'css/client/validation.css' %}" rel="stylesheet" type="text/css" />
{% endblock css %}

{% block content %} 
  <!-- Content -->

  <div id="content-main">
    <form 
    method="post" 
    id="client_form" 
    class="border border-secondary"
    action=""
    novalidate
    >
      {% csrf_token %}
      <div>
        <fieldset class="module aligned">
          <legend>
            <strong> Crear nuevo cliente</strong>
          </legend>
          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_nombre">Nombre:</label>
            </div>
            <div class="col-1">
              <input
              type="text"
              name="nombre"
              maxlength="200"
              required
              id="id_nombre"
              placeholder = "Nombre del cliente"
              spellcheck="false"
              />
            </div>
          </div>

          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_apellido">Apellido:</label>
            </div>
            <div class="col-1">
              <input
                type="text"
                name="apellido"
                maxlength="200"
                required
                id="id_apellido"
                spellcheck="false"
                placeholder = "Apellido del cliente"
              />
            </div>
          </div>
          
          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_cedula">Cedula:</label>
            </div>
            <div class="col-4">
              <input
              type="text"
              name="cedula"
              id="id_cedula"
              {% comment %} spellcheck="false"
              data-ms-editor="true" {% endcomment %}
              placeholder = "Número de 8 a 10 digitos"
              minlength="8" 
              maxlength="10"
              pattern="\d{8,10}"
              required
              />
              <span class="errorcedula" aria-live="polite"></span>
            </div>
            {% comment %} <div class="col-1" id="_id_cedula"><span class="errorcedula" aria-live="polite"></span></div> {% endcomment %}
            <script src="{% static 'js/client/validation-cedula.js' %}"></script>
          </div>
          
          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_telefono">Telefono:</label>
            </div>
            <div class="col-4">
              <input
              type="text"
              name="telefono"
              maxlength="10"
              minlength="10"
              required
              id="id_telefono"
              {% comment %} spellcheck="false"
              data-ms-editor="true" {% endcomment %}
              pattern="\d{10}"
              placeholder = "Número de 10 digitos"
              />
              <span class="errorcelular" aria-live="polite"></span>
            </div>
            <script src="{% static 'js/client/validation-celular.js' %}"></script>
          </div>
          
          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_direccion">Direccion:</label>
            </div>
            <div class="col-1">
              <input
              type="text"
              name="direccion"
              maxlength="200"
              required
              id="id_direccion"
              placeholder = "Dirección vivienda del cliente"
              spellcheck="false"
              />
            </div>
          </div>
          
          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_direccion2">Direccion 2:</label>
            </div>
            <div class="col-1">
              <input
                type="text"
                name="direccion2"
                maxlength="200"
                id="id_direccion2"
                placeholder = "Dirección trabajo cliente"
                spellcheck="false"
                />
            </div>
          </div>
          
          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_ref1">Referencia 1:</label>
            </div>
            <div class="col-1">
              <input
                type="text"
                name="ref1"
                class="vTextField"
                maxlength="200"
                id="id_ref1"
                spellcheck="false"
                data-ms-editor="true"
                placeholder = "Referencia del cliente"
                />
            </div>
          </div>

          <div class="row ml-4 mt-4 mb-4">
            <div class="col-1">
              <label class="required" for="id_telefono_ref1">Telefono referencia 1:</label>
            </div>
            <div class="col-4">
              <input
              type="text"
              name="telefono_ref1"
              maxlength="10"
              minlenghht="10"
              id="id_telefono_ref1"
              placeholder = "Telefono de ref. cliente"
              pattern="\d{8,10}"
              spellcheck="false"
              />
              <span class="errorcelularref1" aria-live="polite"></span>
            </div>
            <script src="{% static 'js/client/validation-celular-ref1.js' %}"></script>
          </div>

        </fieldset>

        <div class="row float-left mt-3">
          <button type="submit" class="btn btn-light ml-3 mr-3" name="save">
            <strong><h4>Guardar</h4></strong>
          </button>
          <button class="btn btn-light ml-3 mr-3">
            <strong><h4><a href="{% url 'clients-home' %}" class="text-dark">Cancel</a></h4></strong>
          </button>
        </div>

        </div>
      </div>
    </form>

    
  </div>


  <!-- END Content -->
{% endblock content %}

{% block footer %} 
<div id="footer"></div>
{% endblock footer %}

source/Docker-backend/pawnshop/templates/clients/clientes_home.html
{% extends '_base.html' %} {% load static %} {% block title %}
<title>Add loan | Django site admin</title>
{% endblock title %} {% block css %} {% endblock css %} {% block javascript %}
<script src="{% static 'js/client/clients-pie-charts.js' %}"></script>
{% comment %}
<script src="{% static 'js/client/clients-bar-charts.js' %}"></script>
{% endcomment %} {% endblock javascript %} {% block content %}

<div class="Superior">
  <div class="row float-left mt-1 ml-3 mb-1 mr-1">
    <h2 style=""><strong>Resumen de Clientes</strong></h2>
  </div>
  <div class="row float-right mt-1 ml-3 mb-1 mr-1">
    <a class="p-2 text-dark" href="{% url 'clients-crear' %}">
      <img src="{% static 'images/base/add.png' %}" alt="" height="25" />
    </a>
    <a class="p-2 text-dark" href="{% url 'clients-buscar' %}">
      <img src="{% static 'images/base/search3.png' %}" alt="" height="25" />
    </a>
  </div>
</div>

<div class=" " style="display: flex; margin-left: 50px">
  <div class="col-7 card ml-2 mr-2">
    <div class="card-body">
      <h4 class="card-title" style="margin-left: 250px">Clientes Regitrados</h4>
      <p class="card-description" style="margin-left: 250px">
        Información básica de clientes
      </p>

      <div
        class="tablewrapper"
        style="width: 700px; margin-left: 60px; max-height: 400px"
      >
        <table class="table">
          <thead>
            <tr class="h4 text-center">
              <th scope="col">ID</th>
              <th scope="col">Nombre</th>
              <th scope="col">Apellido</th>
              <th scope="col">Cédula</th>
            </tr>
          </thead>
          <tbody id="id_tabla_clients" class="h4 text-center">
            {% for cliente in clientes %}
            <tr>
              <th scope="row">{{cliente.pk}}</th>
              <td>{{cliente.nombre}}</td>
              <td>{{cliente.apellido}}</td>
              <td>{{cliente.cedula}}</td>
            </tr>
            {% endfor %}
          </tbody>
        </table>
      </div>
    </div>
  </div>
  <div class="col-4.7 flex-box" >
    
    <div class="card " style="margin-right:20px">
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de clientes creados</h4>
        <p class="card-description text-center"> Entre Enero y mayo de 2022</p>
        <div class="chart-container" style=" margin: 50px; ">
          <canvas id="bar-chart" ></canvas>
        </div>
      </div>
    </div>
        <div class="card" style="margin-right:20px" >
      <div class="card-body">
        <h4 class="card-title text-center">Cantidad de clientes creados</h4>
        <div class="chart-container" style="width: 30%; margin-left: 160px">
          <canvas height="60px" id="pie-chart"></canvas>
        </div>
      </div>
  </div> 
  
  </div>
</div>

{% endblock content %}